
// ═══════════════════════════════════════════════════════════════════════════════
// Keywords & Channel Lists — Single source of truth for classification data
// ═══════════════════════════════════════════════════════════════════════════════

// ─── Entertainment Keywords (strong negative signal) ─────────────────────────
const entertainmentKeywords = [
  // Music & Songs
  "music", "music video", "music album", "video song", "audio song", "lyrical",
  "video lyrical", "songs", "bgm", "remix", "cover song", "karaoke", "jukebox",
  "melody", "album", "singer", "playback", "super hits", "hit song", "chartbuster",
  "concert", "music festival", "beatbox", "lo-fi", "lofi", "ambient", "sleep music",
  "lip sync", "singing challenge", "dance challenge", "bass boosted", "slowed reverb",
  "mashup", "medley", "acoustic version", "unplugged", "live performance",
  "rap", "hip hop", "edm", "dubstep", "trap music", "pop song", "rock song",
  "country music", "r&b", "reggaeton", "classical music",
  // Mix / Full Video / Compilation patterns
  "full video", "full movie", "full film", "full episode", "full song",
  "mix video", "video mix", "nonstop", "non stop",
  "greatest of all time", "goat", "all time hits",
  "4k video", "hd video", "full hd", "ultra hd",
  "video jukebox", "back to back", "hits collection",
  "blockbuster", "superhit", "mega hit", "trending song",

  // Regional Indian Entertainment
  "bollywood", "tollywood", "kollywood", "mollywood", "sandalwood",
  "saregama", "t-series", "zee music", "sony music", "lahari music", "aditya music",
  "sun tv", "zee tamil", "vijay tv", "star maa", "colors tv",
  "galatta", "open talk", "rapid fire", "bigg boss",
  // Indian cinema actors & directors (strong entertainment signal)
  "thalapathy", "thalapathy vijay", "rajinikanth", "kamal haasan",
  "ajith kumar", "suriya", "dhanush", "sivakarthikeyan", "vikram",
  "allu arjun", "prabhas", "ram charan", "mahesh babu", "jr ntr",
  "shah rukh khan", "salman khan", "aamir khan", "hrithik roshan",
  "ranveer singh", "ranbir kapoor", "deepika padukone", "alia bhatt",
  "yuvan shankar raja", "ar rahman", "anirudh ravichander", "thaman",
  "venkat prabhu", "shankar director", "atlee", "lokesh kanagaraj",
  "ss rajamouli", "mani ratnam", "kalpathi s. agoram",
  "million views", "22 million",
  "hook step", "kuthu", "item song", "romantic", "love story",
  "saree", "mehndi", "rangoli", "pooja",
  "nollywood", "telenovela", "desi", "filmi",

  // Movies & Shows
  "movie", "trailer", "teaser", "short film", "web series", "series",
  "behind the scenes", "red carpet", "award show",
  "netflix", "amazon prime", "hotstar", "disney plus", "jio cinema",
  "hbo max", "hulu", "peacock", "paramount plus", "apple tv",
  "korean series", "korean drama", "k-drama", "chinese drama", "drama",
  "anime episode", "manga", "reality show", "game show", "dating show",
  "talent show", "singing show", "dance show",
  "actor", "actress", "celebrity", "celebrity news", "celebrity gossip",
  "movie review", "film review", "binge watch", "watchlist", "movie recap",
  "ending explained", "fan theory", "easter eggs",
  "scene pack", "edit", "fancam", "fan edit",

  // Comedy & Pranks
  "comedy", "funny", "funny videos", "funny moments", "funny compilation",
  "funniest moments", "meme", "meme compilation", "prank", "skit", "parody",
  "spoof", "reaction", "reaction video", "roast", "diss track",
  "try not to laugh", "try not to cry", "fail compilation",
  "best moments", "epic moments", "bloopers", "outtakes", "gag reel",
  "stand up comedy", "standup", "comedian", "joke", "jokes",
  "cringe", "cringe compilation", "dark humor", "offensive jokes",

  // Vlogs & Lifestyle
  "vlog", "travel vlog", "family vlog", "daily vlog", "day in my life",
  "grwm", "get ready with me", "haul", "unboxing", "room tour", "house tour",
  "car tour", "shopping spree", "what i eat", "gym vlog",
  "outfit of the day", "ootd", "fashion", "style", "outfit", "clothing",
  "accessories", "jewelry", "makeup", "skincare", "beauty", "cosmetics",
  "nail art", "hairstyle", "thrift haul", "try on haul", "declutter",
  "morning routine", "night routine", "skincare routine", "self care",
  "apartment tour", "dorm tour", "closet tour",
  "life update", "q&a", "ask me anything", "ama",

  // Sports & Gaming
  "gameplay", "gaming", "let's play", "walkthrough", "playthrough",
  "highlights", "match highlights", "goals", "cricket", "ipl", "football",
  "soccer", "basketball", "nba", "fifa", "esports",
  "speedrun", "world record", "clutch", "montage", "kill streak",
  "fortnite", "minecraft", "gta", "valorant", "call of duty", "apex legends",
  "league of legends", "pubg", "roblox", "elden ring", "zelda",
  "ps5", "xbox", "nintendo", "twitch", "streamer",
  "wrestling", "wwe", "ufc", "mma", "boxing match",
  "tennis", "golf", "f1", "formula 1", "nascar", "baseball", "mlb",
  "hockey", "nhl", "volleyball", "swimming", "olympics highlights",

  // Relationships & Personal
  "husband", "wife", "couple", "boyfriend", "girlfriend", "family", "friends",
  "relationship", "pregnancy", "marriage", "wedding", "engagement",
  "baby shower", "gender reveal", "proposal",
  "birthday", "anniversary", "farewell", "reunion",
  "breakup", "divorce", "cheating", "caught cheating", "love triangle",
  "dating tips", "dating advice", "pickup lines", "crush",

  // News & Current Events (non-academic)
  "breaking news", "headlines", "news update", "latest news", "live news",
  "bombing", "blast", "attack", "kills", "dead", "injured", "casualties",
  "protest", "riot", "scandal", "controversy", "arrested", "detained",
  "condemns", "mea condemns", "breaking",
  "election results", "political rally", "political debate", "campaign",

  // Food & Cooking (non-educational)
  "food review", "street food", "food challenge", "eating challenge",
  "spicy food", "fast food", "junk food", "taste test", "blind taste test",
  "food tour", "restaurant review", "cooking competition",
  "recipe", "recipes", "cooking", "cook with", "village cooking",
  "biryani", "mutton", "chicken fry", "chicken curry", "fish fry", "fish curry",
  "paneer", "dal", "sambar", "rasam", "idli", "dosa", "paratha", "naan",
  "kebab", "tandoori", "tikka", "masala", "gravy", "korma", "pulao",
  "bone marrow", "roast chicken", "grilled", "deep fried", "fried rice",
  "cake recipe", "baking", "dessert recipe", "sweet recipe", "snack recipe",
  "how to cook", "homemade", "kitchen tips", "kitchen hacks",
  "food vlog", "what i eat", "meal prep", "lunch box", "tiffin",
  "bbq", "barbecue", "smoker", "pit master", "grill master",
  "pasta recipe", "pizza recipe", "burger recipe", "sandwich recipe",
  "smoothie", "juice recipe", "cocktail recipe",

  // Supernatural & Pseudoscience
  "ghost", "haunted", "paranormal", "horror", "creepypasta", "scary",
  "conspiracy theory", "flat earth", "alien", "ufo sighting",
  "astrology", "horoscope", "zodiac sign", "tarot reading", "psychic",
  "numerology", "superstition",

  // Miscellaneous Entertainment
  "entertainment", "shorts", "youtube shorts", "promo", "sponsored",
  "ad", "advertisement", "trending", "viral", "challenge",
  "mukbang", "asmr", "storytime", "satisfying", "oddly satisfying",
  "tiktok", "pet video", "cute animals", "dog video", "cat video",
  "luxury", "rich life", "flex", "exposed", "cancelled", "tea spill",
  "drama alert", "beef",
  "celebration", "festival", "holiday", "vacation", "travel", "adventure",
  "road trip", "backpacking", "camping", "hiking",
  "cwc", "cook with comali",
  "graduation", "trip",
  "tier list", "ranking", "top 10", "worst to best",
  "iceberg explained", "rabbit hole", "deep web", "dark web",
  "giveaway", "free iphone", "free giveaway", "subscriber special",
  "face reveal", "car reveal", "transformation", "glow up",
  "24 hour challenge", "overnight challenge", "last to leave",
  "extreme", "insane", "impossible", "gone wrong", "went wrong",

  // YouTube Mix / auto-playlist patterns
  "mix -",
  "erobb221",
  "emoney"
];

// ─── Educational Keywords (200+ terms, word-boundary safe) ───────────────────
const educationalKeywords = [
  // Programming & Tech
  "tutorial", "how to", "explained", "lesson", "course", "lecture",
  "programming", "coding", "algorithm", "data structure", "javascript",
  "python", "react", "nodejs", "typescript", "database", "frontend",
  "backend", "fullstack", "devops", "machine learning", "deep learning",
  "neural network", "artificial intelligence", "computer science",
  "software engineering", "system design", "web development",
  "app development", "android development", "ios development",
  "api", "sql", "linux", "docker", "kubernetes", "cloud computing",
  "cybersecurity", "blockchain", "compiler", "operating system",
  "git tutorial", "github actions", "ci cd", "continuous integration",
  "microservices", "rest api", "graphql", "websocket", "grpc",
  "html", "css", "dom manipulation", "responsive design", "tailwind",
  "bootstrap", "sass", "webpack", "vite", "nextjs", "nuxtjs", "svelte",
  "angular", "vue", "django", "flask", "spring boot", "express",
  "rust programming", "golang", "c++", "c programming", "java programming",
  "kotlin", "swift programming", "dart", "flutter", "react native",
  "ruby on rails", "php", "laravel", "assembly language",
  "regex", "design patterns", "solid principles", "clean code",
  "refactoring", "testing", "unit test", "integration test",
  "mongodb", "postgresql", "mysql", "redis", "elasticsearch",
  "aws tutorial", "azure tutorial", "gcp tutorial",
  "terraform", "ansible", "jenkins", "nginx",
  "computer networking", "tcp ip", "http protocol", "dns",
  "encryption", "hashing", "authentication", "oauth",
  "data pipeline", "etl", "data warehouse", "apache spark", "pyspark", "hadoop",
  "llm", "large language model", "prompt engineering", "chatgpt tutorial",
  "langchain", "rag", "retrieval augmented", "fine tuning",
  "generative ai", "transformer model", "attention mechanism",
  "computer vision", "opencv", "image recognition", "object detection",
  "nlp", "natural language processing", "sentiment analysis",
  "reinforcement learning", "supervised learning", "unsupervised learning",

  // Science
  "physics", "chemistry", "biology", "astronomy", "quantum mechanics",
  "thermodynamics", "electromagnetism", "genetics", "dna", "cell biology",
  "microbiology", "neuroscience", "ecology", "climate science",
  "organic chemistry", "biochemistry", "astrophysics", "scientific method",
  "photosynthesis", "mitosis", "meiosis", "osmosis", "diffusion",
  "periodic table", "chemical reaction", "molecular biology",
  "anatomy", "physiology", "human body", "immune system",
  "evolution", "natural selection", "taxonomy", "biodiversity",
  "planetary science", "solar system", "black hole", "dark matter",
  "relativity", "string theory", "particle physics", "higgs boson",
  "nuclear physics", "radioactivity", "electromagnetic spectrum",
  "plate tectonics", "geology", "meteorology", "oceanography",
  "environmental science", "renewable energy", "sustainability",
  "carbon footprint", "greenhouse effect", "ozone layer",
  "stem", "scientific research", "lab experiment",

  // Math
  "calculus", "algebra", "geometry", "trigonometry", "statistics",
  "probability", "linear algebra", "differential equation", "mathematical",
  "theorem", "logarithm", "number theory", "discrete math",
  "integral", "derivative", "matrix", "vector", "polynomial",
  "complex number", "exponential", "combinatorics", "graph theory",
  "set theory", "boolean algebra", "mathematical proof",
  "numerical methods", "fourier transform", "laplace transform",
  "real analysis", "abstract algebra", "topology",
  "binomial theorem", "permutation", "mean median mode",
  "standard deviation", "regression", "correlation", "hypothesis testing",
  "bayesian", "stochastic", "optimization",

  // Medicine & Health Science
  "medical", "medicine", "pharmacology", "pathology", "cardiology",
  "neurology", "oncology", "dermatology", "orthopedics", "radiology",
  "surgery", "clinical", "diagnosis", "treatment", "patient care",
  "epidemiology", "public health", "vaccine", "immunology",
  "mental health", "cognitive behavioral", "therapy techniques",
  "nutrition science", "dietetics", "metabolism", "endocrinology",
  "first aid", "cpr training", "nursing", "paramedic",
  "medical terminology", "anatomy lecture", "dissection",

  // Engineering
  "civil engineering", "mechanical engineering", "electrical engineering",
  "electronics", "circuit design", "pcb design", "arduino", "raspberry pi",
  "embedded systems", "iot", "internet of things", "plc programming",
  "cad", "3d modeling", "solidworks", "autocad", "matlab",
  "structural engineering", "fluid mechanics", "material science",
  "aerospace engineering", "robotics", "automation",
  "signal processing", "control systems", "power systems",
  "vlsi", "fpga", "verilog", "vhdl", "semiconductor",
  "telecommunications", "antenna design", "rf engineering",
  "biomedical engineering", "chemical engineering", "industrial engineering",

  // Academic — Humanities & Social Sciences
  "history of", "economics", "political science", "philosophy",
  "sociology", "psychology", "anthropology", "archaeology", "linguistics",
  "literature analysis", "critical thinking", "cognitive bias",
  "macroeconomics", "microeconomics", "geopolitics", "constitutional",
  "civil rights", "world war", "ancient civilization",
  "renaissance", "enlightenment", "industrial revolution",
  "cold war", "colonialism", "imperialism", "nationalism",
  "democracy", "communism", "socialism", "capitalism explained",
  "supply and demand", "inflation", "monetary policy", "fiscal policy",
  "game theory", "behavioral economics", "development economics",
  "international relations", "diplomacy", "united nations",
  "ethics", "moral philosophy", "epistemology", "metaphysics",
  "existentialism", "stoicism", "logical fallacy",
  "cognitive psychology", "developmental psychology", "social psychology",
  "clinical psychology", "freud", "jung", "maslow",
  "criminology", "forensic science", "law explained", "legal studies",
  "constitutional law", "human rights", "justice system",
  "cultural studies", "gender studies", "media studies",
  "literary criticism", "shakespeare analysis", "poetry analysis",
  "art history", "renaissance art", "modern art", "art analysis",
  "music theory", "composition theory", "film analysis", "film studies",

  // Personal Finance & Investing (educational)
  "personal finance", "budgeting", "compound interest", "retirement planning",
  "index fund", "mutual fund", "tax planning", "estate planning",
  "financial literacy", "credit score", "debt management",
  "stock analysis", "fundamental analysis", "technical analysis",
  "value investing", "dividend investing", "portfolio diversification",
  "cryptocurrency explained", "bitcoin explained", "defi explained",
  "real estate investing", "passive income strategy",

  // Professional Skills
  "business strategy", "management", "finance", "accounting",
  "marketing strategy", "product management", "project management",
  "agile", "scrum", "design thinking", "ux design", "ui design",
  "graphic design", "typography", "color theory", "branding",
  "public speaking", "leadership", "entrepreneurship",
  "data analysis", "data science", "visualization",
  "resume writing", "interview preparation", "career advice",
  "time management", "productivity tips", "goal setting",
  "communication skills", "negotiation skills", "conflict resolution",
  "emotional intelligence", "mindfulness", "stress management",
  "remote work tips", "freelancing guide", "networking tips",
  "business plan", "pitch deck", "startup funding",
  "supply chain management", "operations management", "lean manufacturing",
  "six sigma", "quality assurance", "risk management",

  // Language Learning
  "language learning", "grammar lesson", "vocabulary", "pronunciation",
  "conjugation", "reading comprehension", "writing skills", "essay writing",
  "ielts", "toefl", "gre preparation",
  "english lesson", "spanish lesson", "french lesson", "german lesson",
  "japanese lesson", "chinese lesson", "korean lesson", "hindi lesson",
  "arabic lesson", "portuguese lesson", "italian lesson", "russian lesson",
  "duolingo", "rosetta stone", "language exchange",
  "idioms", "phrasal verbs", "prepositions", "articles grammar",

  // Education & Exam Prep
  "exam preparation", "board exam", "entrance exam", "competitive exam",
  "jee preparation", "neet preparation", "upsc", "gate exam",
  "sat preparation", "act preparation", "gmat preparation",
  "ap exam", "ib curriculum", "gcse", "a level",
  "scholarship guide", "study abroad", "college application",
  "dissertation", "thesis writing", "research methodology",
  "academic writing", "citation", "bibliography", "peer review",

  // General education signals
  "step by step", "beginner guide", "complete guide", "crash course",
  "full course", "free course", "masterclass", "workshop",
  "certification", "exam prep", "study guide", "fundamentals",
  "introduction to", "basics of", "deep dive", "comprehensive guide",
  "documentation", "research",
  "cheat sheet", "roadmap", "learning path", "curriculum",
  "quick reference", "best practices", "industry standard",
  "case study", "whitepaper", "technical review", "code review",
  "hands on", "practical guide", "project based", "build from scratch",
  "live coding", "pair programming", "code walkthrough"
];

// ─── Known Educational Channels ─────────────────────────────────────────────
const knownEducationalChannels = [
  // Science & Math
  "3blue1brown", "khan academy", "crashcourse", "veritasium", "vsauce",
  "minutephysics", "numberphile", "computerphile", "kurzgesagt", "ted-ed",
  "ted", "smarter every day", "real engineering", "practical engineering",
  "two minute papers", "the organic chemistry tutor", "professor leonard",
  "patrickjmt", "brilliant", "zach star", "tibees", "mathologer",
  "blackpenredpen", "flammable maths", "dr trefor bazett",
  "michael penn", "professor dave explains", "sci show", "asap science",
  "minuteearth", "the action lab", "thought emporium", "nilered",
  "periodic videos", "sixty symbols", "deep sky videos",
  "dr. becky", "arvin ash", "sabine hossenfelder", "pbs space time",
  "fermilab", "domain of science", "up and atom",
  "science asylum", "steve mould", "answers with joe",
  "dr mike", "medlife crisis", "institute of human anatomy",
  "chubbyemu", "osmosis", "ninja nerd", "armando hasudungan",

  // Programming & Tech
  "fireship", "traversy media", "the coding train", "cs dojo",
  "freecodecamp", "web dev simplified", "net ninja", "academind",
  "programming with mosh", "corey schafer", "sentdex",
  "techworld with nana", "theo", "jack herrington", "kevin powell",
  "the primeagen", "ben awad", "clement mihailescu", "neetcode",
  "william lin", "tech with tim", "codewithharry", "code with harry",
  "apna college", "love babbar", "striver", "take u forward",
  "jenny's lectures", "gate smashers", "abdul bari", "mycodeschool",
  "brocode", "bro code", "codevolution", "dave gray", "coding addict",
  "javascript mastery", "lama dev", "sonny sangha", "clever programmer",
  "pedro tech", "developedbyed", "coder coder",
  "caleb curry", "thenewboston", "derek banas", "tim buchalka",
  "john smilga", "hitesh choudhary", "codestackr", "james q quick",
  "fun fun function", "mattpocock", "josh tried coding",
  "hyperplexed", "web dev cody", "slaying the dragon",
  "arjan codes", "anthonygg", "dreams of code", "typecraft",
  "thecherno", "javidx9", "low level learning", "jacob sorber",
  "casey muratori", "ben eater", "sebastian lague",
  "george hotz", "tsoding", "teej dv",

  // AI & Data Science
  "yannic kilcher", "lex fridman", "andrej karpathy", "jeremy howard",
  "statquest", "ritvikmath", "krish naik", "codebasics",
  "data school", "ken jee", "daniel bourke",
  "matthew berman", "sam witteveen", "dave ebbelaar", "james briggs",
  "matt wolfe", "ai explained", "ai jason", "bycloud",
  "deeplizard", "aleksa gordic", "the ai epiphany",
  "3blue1brown", "welch labs", "luis serrano",

  // University & Courses
  "mit opencourseware", "stanford online", "stanford", "harvard",
  "yale courses", "nptel", "neso academy", "iit", "bits pilani",
  "edureka", "simplilearn", "intellipaat", "great learning",
  "coursera", "edx", "udemy", "pluralsight", "linkedin learning",
  "unacademy", "byju", "vedantu", "physicswallah",
  "oxford university", "cambridge university", "caltech",
  "berkeley", "princeton", "cornell", "columbia university",
  "imperial college", "ucl", "university of michigan",
  "the royal institution", "world science festival",

  // History, Geography & Social Science
  "oversimplified", "extra credits", "historia civilis",
  "cgp grey", "real life lore", "not just bikes",
  "mark rober", "derek muller", "tom scott", "polymatter", "wendover",
  "half as interesting", "economics explained", "visual politik",
  "kings and generals", "epic history tv", "history matters",
  "invicta", "the great war", "world war two",
  "feature history", "armchair historian", "toldinstone",
  "james jani", "johnny harris", "vox", "kurzgesagt",
  "atlas pro", "geography now", "rare earth",
  "knowing better", "today i found out", "thoughty2",
  "joe scott", "mustard", "neo", "coldfusion",

  // Finance & Business Education
  "graham stephan", "andrei jikh", "the plain bagel",
  "two cents", "how money works", "patrick boyle",
  "one percent better", "ali abdaal", "thomas frank",
  "mike and matty", "nischa", "jeff su", "matt d'avella",

  // Indian Tech & Education
  "telusko", "durga software", "navin reddy", "kudvenkat",
  "programming knowledge", "cyberdude", "cyberdude networks",
  "tamil hacks", "guvi", "scaler", "coding ninjas",
  "prepinsta", "interviewbit", "geeksforgeeks",
  "pepcoding", "aditya verma", "anuj bhaiya", "college wallah",
  "knowledge gate", "education 4u", "sanchit jain",
  "babbar", "fraz", "arsh goyal", "lakshay kumar",

  // Cloud & DevOps
  "google cloud", "google developers", "hack2skill", "google cloud tech",
  "aws", "amazon web services", "microsoft azure", "azure",
  "google for developers",
  "acloud guru", "cloud academy", "digital cloud training",
  "that devops guy", "techno tim", "networkchuck",
  "david bombal", "john savill", "learn linux tv",

  // Design & Creative (educational)
  "the futur", "flux academy", "envato tuts+", "dansky",
  "will paterson", "satori graphics", "charli marie",
  "ux mastery", "malewicz", "jesse showalter"
];

// ─── Motivational Messages (keyed by entertainment category) ─────────────────
const distractingKeywordMessages = {
  music: "Silence can be golden when you're learning.",
  comedy: "Laughter is great, but focus fuels progress!",
  movie: "Blockbusters can wait. Build your future now.",
  prank: "Real success isn't a prank!",
  reaction: "React to your goals instead!",
  vlog: "Make your own story worth vlogging!",
  shorts: "Think long-term. Skip the Shorts.",
  entertainment: "Fun's great, but growth is better.",
  trailer: "Focus on the bigger picture, not just trailers.",
  gameplay: "Build your own game of success!",
  dance: "Dance through your work and focus on growth!",
  funny: "Laughter fades, but learning lasts.",
  meme: "Memes are cool, but mastering skills is cooler.",
  celebrity: "Become your own celebrity with skills!",
  challenge: "Challenge yourself to stay focused!",
  viral: "Chase knowledge, not viral trends.",
  drama: "Focus on becoming the star of your own future.",
  fashion: "Fashion fades, knowledge is forever.",
  makeup: "Make up your mind to learn something new!",
  travel: "Travel the road of knowledge!",
  gaming: "Level up your skills, not just your character.",
  gossip: "Skip the gossip. Build something meaningful.",
  anime: "Your real-life arc needs effort too!",
  sports: "Train your mind like athletes train their bodies.",
  romance: "Fall in love with learning instead.",
  horror: "The scariest thing is wasted potential.",
  asmr: "Relax later. Right now, learn something new.",
  mukbang: "Feed your brain, not just your eyes.",
  unboxing: "Unbox your potential with a new skill.",
  haul: "The best haul is a haul of knowledge.",
  cooking: "Cook up a great career with focused learning.",
  recipe: "The best recipe is: mix focus + hard work!",
  biryani: "Feed your brain, not just your stomach!",
  pet: "Your future self will thank you for studying now.",
  luxury: "True wealth is built with knowledge and skills.",
  conspiracy: "Focus on facts and proven knowledge.",
  astrology: "Your stars say: time to learn something real!",
  streamer: "Stream your focus into productive learning.",
  wrestling: "Wrestle with challenging problems instead.",
  boxing: "Fight for your future — hit the books!",
  news: "Headlines fade. Skills compound forever.",
  gossip: "Skip the drama. Build your empire.",
  tiktok: "Scroll less. Learn more.",
  cringe: "The only cringe is not investing in yourself.",
  roast: "Roast procrastination, not people.",
  scam: "Don't get scammed by distractions!",
  dating: "Date your goals. Commit to growth.",
  mix: "Mix up your routine with learning instead!",
  erobb221: "Do not watch this streamer, he is a scammer"
};

// ─── Strong Educational Title Signals (regex) ───────────────────────────────
const strongEduSignals = /\b(tutorial|course|lecture|lesson|explained|how to code|programming|coding|algorithm|data structure|machine learning|deep learning|web development|full stack|devops|system design|interview prep|dsa|competitive programming|certification|crash course|masterclass|workshop|step by step|beginner guide|complete guide|computer science|software engineering|artificial intelligence|neural network|cybersecurity|data science|calculus|algebra|physics|chemistry|biology|economics|philosophy|history of|medical|engineering|exam preparation|study guide|research methodology|code review|live coding|hands on|build from scratch|project based|full course)\b/i;
